const FILTER_CATALOG = 'FILTER_CATALOG';
const GET_DATA = 'GET_DATA';
const SET_MINVALUE = 'SET_MINVALUE';
const SET_MAXVALUE = 'SET_MINVALUE';
const SET_BRANDS = 'SET_BRANDS';
const GET_ALL = 'GET_ALL';

export {
  FILTER_CATALOG,
  GET_DATA,
  SET_MINVALUE,
  SET_MAXVALUE,
  SET_BRANDS,
  GET_ALL
}
